#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RecyclerViewTutorial.Resource", IsApplication=true)]

namespace RecyclerViewTutorial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int anim_out = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int flip = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_left_to_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_right_to_left = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_up = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070006
			public const int blue_light = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int blue_light_focused = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int cardview_dark_background = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_light_background = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_shadow_end_color = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cardview_shadow_start_color = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int holo_blue_dark = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int holo_blue_dark_focused = 2131165188;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000e
			public const int action_bar_content_inset_material = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int action_bar_default_height_material = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int action_bar_default_padding_end_material = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int action_bar_default_padding_start_material = 2131034124;
			
			// aapt resource value: 0x7f050015
			public const int action_bar_elevation_material = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int action_bar_icon_vertical_padding_material = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int action_bar_overflow_padding_end_material = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int action_bar_overflow_padding_start_material = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int action_bar_subtitle_bottom_margin_material = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int action_bar_subtitle_top_margin_material = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int action_button_min_height_material = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int action_button_min_width_material = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int action_button_min_width_overflow_material = 2131034134;
			
			// aapt resource value: 0x7f05002f
			public const int button_elevation_material = 2131034159;
			
			// aapt resource value: 0x7f050032
			public const int button_inset_horizontal_material = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int button_inset_vertical_material = 2131034161;
			
			// aapt resource value: 0x7f050034
			public const int button_padding_horizontal_material = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int button_padding_vertical_material = 2131034163;
			
			// aapt resource value: 0x7f050030
			public const int button_pressed_z_material = 2131034160;
			
			// aapt resource value: 0x7f050001
			public const int cardview_compat_inset_shadow = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_default_elevation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_default_radius = 2131034115;
			
			// aapt resource value: 0x7f050037
			public const int control_corner_material = 2131034167;
			
			// aapt resource value: 0x7f050035
			public const int control_inset_material = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int control_padding_material = 2131034166;
			
			// aapt resource value: 0x7f05005f
			public const int date_picker_date_label_size = 2131034207;
			
			// aapt resource value: 0x7f050065
			public const int date_picker_day_height = 2131034213;
			
			// aapt resource value: 0x7f050064
			public const int date_picker_day_of_week_height = 2131034212;
			
			// aapt resource value: 0x7f050061
			public const int date_picker_day_of_week_text_size = 2131034209;
			
			// aapt resource value: 0x7f050067
			public const int date_picker_day_selector_radius = 2131034215;
			
			// aapt resource value: 0x7f050062
			public const int date_picker_day_text_size = 2131034210;
			
			// aapt resource value: 0x7f050066
			public const int date_picker_day_width = 2131034214;
			
			// aapt resource value: 0x7f050063
			public const int date_picker_month_height = 2131034211;
			
			// aapt resource value: 0x7f050060
			public const int date_picker_month_text_size = 2131034208;
			
			// aapt resource value: 0x7f05005e
			public const int date_picker_year_label_size = 2131034206;
			
			// aapt resource value: 0x7f050055
			public const int datepicker_component_width = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int datepicker_dialog_width = 2131034198;
			
			// aapt resource value: 0x7f05005a
			public const int datepicker_header_height = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int datepicker_header_text_size = 2131034203;
			
			// aapt resource value: 0x7f05005d
			public const int datepicker_list_year_activated_label_size = 2131034205;
			
			// aapt resource value: 0x7f05005c
			public const int datepicker_list_year_label_size = 2131034204;
			
			// aapt resource value: 0x7f050057
			public const int datepicker_selected_date_day_size = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int datepicker_selected_date_month_size = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int datepicker_selected_date_year_size = 2131034201;
			
			// aapt resource value: 0x7f05006b
			public const int datepicker_view_animator_height = 2131034219;
			
			// aapt resource value: 0x7f050054
			public const int datepicker_year_label_height = 2131034196;
			
			// aapt resource value: 0x7f05006a
			public const int day_picker_button_margin_top = 2131034218;
			
			// aapt resource value: 0x7f050068
			public const int day_picker_padding_horizontal = 2131034216;
			
			// aapt resource value: 0x7f050069
			public const int day_picker_padding_top = 2131034217;
			
			// aapt resource value: 0x7f05003e
			public const int dialog_list_padding_vertical_material = 2131034174;
			
			// aapt resource value: 0x7f05003b
			public const int dialog_padding_material = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int dialog_padding_top_material = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int edit_text_inset_bottom_material = 2131034170;
			
			// aapt resource value: 0x7f050038
			public const int edit_text_inset_horizontal_material = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int edit_text_inset_top_material = 2131034169;
			
			// aapt resource value: 0x7f05002e
			public const int floating_window_margin_bottom = 2131034158;
			
			// aapt resource value: 0x7f05002b
			public const int floating_window_margin_left = 2131034155;
			
			// aapt resource value: 0x7f05002d
			public const int floating_window_margin_right = 2131034157;
			
			// aapt resource value: 0x7f05002c
			public const int floating_window_margin_top = 2131034156;
			
			// aapt resource value: 0x7f05002a
			public const int floating_window_z = 2131034154;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050012
			public const int list_item_padding_horizontal_material = 2131034130;
			
			// aapt resource value: 0x7f050009
			public const int preference_breadcrumbs_padding_end_material = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int preference_breadcrumbs_padding_start_material = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int preference_fragment_padding_side_material = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int preference_screen_header_padding_side_material = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int preference_screen_header_vertical_padding_material = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int preference_screen_side_margin_material = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int preference_screen_side_margin_negative_material = 2131034118;
			
			// aapt resource value: 0x7f050041
			public const int progress_bar_height_material = 2131034177;
			
			// aapt resource value: 0x7f05003f
			public const int seekbar_track_background_height_material = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int seekbar_track_progress_height_material = 2131034176;
			
			// aapt resource value: 0x7f05003d
			public const int select_dialog_padding_start_material = 2131034173;
			
			// aapt resource value: 0x7f050024
			public const int text_size_body_1_material = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int text_size_body_2_material = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int text_size_button_material = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int text_size_caption_material = 2131034149;
			
			// aapt resource value: 0x7f05001c
			public const int text_size_display_1_material = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int text_size_display_2_material = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int text_size_display_3_material = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int text_size_display_4_material = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int text_size_headline_material = 2131034141;
			
			// aapt resource value: 0x7f050027
			public const int text_size_large_material = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int text_size_medium_material = 2131034152;
			
			// aapt resource value: 0x7f050022
			public const int text_size_menu_material = 2131034146;
			
			// aapt resource value: 0x7f050029
			public const int text_size_small_material = 2131034153;
			
			// aapt resource value: 0x7f05001f
			public const int text_size_subhead_material = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int text_size_subtitle_material_toolbar = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int text_size_title_material = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int text_size_title_material_toolbar = 2131034144;
			
			// aapt resource value: 0x7f050045
			public const int timepicker_am_top_padding = 2131034181;
			
			// aapt resource value: 0x7f050044
			public const int timepicker_ampm_horizontal_padding = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int timepicker_ampm_label_size = 2131034179;
			
			// aapt resource value: 0x7f05004e
			public const int timepicker_center_dot_radius = 2131034190;
			
			// aapt resource value: 0x7f050048
			public const int timepicker_header_height = 2131034184;
			
			// aapt resource value: 0x7f050046
			public const int timepicker_pm_top_padding = 2131034182;
			
			// aapt resource value: 0x7f050049
			public const int timepicker_radial_picker_dimen = 2131034185;
			
			// aapt resource value: 0x7f05004b
			public const int timepicker_radial_picker_horizontal_margin = 2131034187;
			
			// aapt resource value: 0x7f05004a
			public const int timepicker_radial_picker_top_margin = 2131034186;
			
			// aapt resource value: 0x7f05004f
			public const int timepicker_selector_dot_radius = 2131034191;
			
			// aapt resource value: 0x7f05004c
			public const int timepicker_selector_radius = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int timepicker_selector_stroke = 2131034189;
			
			// aapt resource value: 0x7f050047
			public const int timepicker_separator_padding = 2131034183;
			
			// aapt resource value: 0x7f050051
			public const int timepicker_text_inset_inner = 2131034193;
			
			// aapt resource value: 0x7f050050
			public const int timepicker_text_inset_normal = 2131034192;
			
			// aapt resource value: 0x7f050053
			public const int timepicker_text_size_inner = 2131034195;
			
			// aapt resource value: 0x7f050052
			public const int timepicker_text_size_normal = 2131034194;
			
			// aapt resource value: 0x7f050042
			public const int timepicker_time_label_size = 2131034178;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_default_mtrl_shape_blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_btn_blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_new = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_airplane = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_car = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_motorcycle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int k_arrow_down = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int add = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int btnSend = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int card_view = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int icon_doc = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int parent_list_item_expand_arrow = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int recyclerView = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int requisitsText = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int txtName = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int txtSubject = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int viewx = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int row = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int actionbar = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CardView_Dark = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CustomActionBarTheme = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MyActionBar = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			// aapt resource value: 2
			public const int CardView_cardElevation = 2;
			
			// aapt resource value: 3
			public const int CardView_cardMaxElevation = 3;
			
			// aapt resource value: 5
			public const int CardView_cardPreventCornerOverlap = 5;
			
			// aapt resource value: 4
			public const int CardView_cardUseCompatPadding = 4;
			
			// aapt resource value: 6
			public const int CardView_contentPadding = 6;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingBottom = 10;
			
			// aapt resource value: 7
			public const int CardView_contentPaddingLeft = 7;
			
			// aapt resource value: 8
			public const int CardView_contentPaddingRight = 8;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingTop = 9;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
